---
services:
  mia:
    image: "ghcr.io/i1820/mia:latest"
    restart: always
    environment:
      - MIA_TENANT=main
      - MIA_MQTT__HOST=emqx
      - MIA_MQTT__PORT=1883
      - MIA_DATABASE__CONFIG__HOST=mongodb://mongodb
      - MIA_DATABASE__CONFIG__PORT=27017
      - MIA_DATABASE__CONFIG__DATABASE=mia
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  emqx:
    image: emqx/emqx:5.0.0
    ports:
      - 1883:1883
      - 18083:18083
